FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    bzip2 \
    checkinstall \
    cmake \
    curl \
    gfortran \
    git \
    libjasper-dev \
    libjpeg8-dev \
    libpng12-dev \
    libtiff5-dev \
    pkg-config\  
    sudo \
    unp \
    unzip \
    wget \
    yasm
RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev
RUN apt-get install -y libxine2-dev libv4l-dev
RUN apt-get install -y libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
RUN apt-get install -y qt5-default libgtk2.0-dev libtbb-dev
RUN apt-get install -y libatlas-base-dev
RUN apt-get install -y libfaac-dev libmp3lame-dev libtheora-dev
RUN apt-get install -y libvorbis-dev libxvidcore-dev
RUN apt-get install -y libopencore-amrnb-dev libopencore-amrwb-dev
RUN apt-get install -y x264 v4l-utils
RUN apt-get install -y libprotobuf-dev protobuf-compiler
RUN apt-get install -y libgoogle-glog-dev libgflags-dev
RUN apt-get install -y libgphoto2-dev libeigen3-dev libhdf5-dev
RUN apt-get install -y python-dev python-pip python3-dev python3-pip

RUN apt-get -y autoremove && apt-get -y autoclean
RUN rm -rf /var/cache/apt

RUN pip2 install -U pip numpy
RUN pip3 install -U pip numpy

# Install opencv
WORKDIR /opencv
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/3.4.0.zip
RUN wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/3.4.0.zip
RUN unzip opencv.zip
RUN unzip opencv_contrib.zip
WORKDIR /opencv/opencv-3.4.0/build
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=/opencv/opencv_contrib-3.4.0/modules \
      -D BUILD_EXAMPLES=ON ..
RUN make
RUN make install

# Install darknet
RUN git clone https://github.com/pjreddie/darknet /darknet
RUN git checkout f6d861736038da22c9eb0739dca84003c5a5e275
WORKDIR /darknet
RUN make

